"use client";

import { CheckCircle2, RefreshCw, Route } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import { api, type OmsOrder, type OmsReconciliation } from "../../components/api";
import { formatIstTimestamp, formatPrice, titleCase } from "../../lib/formatting";

export function OmsWorkspace({ isAdmin, onMessage }: { isAdmin: boolean; onMessage: (message: string) => void }) {
  const [orders, setOrders] = useState<OmsOrder[]>([]); const [checks, setChecks] = useState<OmsReconciliation[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(() => { setLoading(true); void Promise.all([api.omsOrders(), api.omsReconciliations()]).then(([nextOrders, nextChecks]) => { setOrders(nextOrders); setChecks(nextChecks); }).catch((error: unknown) => onMessage(error instanceof Error ? error.message : "Could not load OMS state")).finally(() => setLoading(false)); }, [onMessage]);
  useEffect(() => { load(); }, [load]);
  const reconcile = async () => { try { const result = await api.runOmsReconciliation(); setChecks((current) => [result, ...current]); onMessage(`Paper OMS reconciliation: ${titleCase(result.status)}.`); } catch (error) { onMessage(error instanceof Error ? error.message : "Reconciliation failed"); } };
  const latest = checks[0]; const unknown = orders.filter((item) => item.status === "UNKNOWN").length;
  return <section><div className="page-toolbar"><div><p className="eyebrow">Paper-only execution control</p><h2 className="page-title">OMS operations</h2><p className="page-copy">Immutable intents and explicit lifecycle events protect paper simulation. No broker adapter or broker order identifier is present.</p></div><div className="flex gap-2"><button className="secondary-button" onClick={load} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />Refresh</button>{isAdmin && <button className="primary-button" onClick={() => void reconcile()}><CheckCircle2 className="h-4 w-4" />Reconcile</button>}</div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="OMS entries" value={orders.length} /><Metric label="Unknown state" value={unknown} tone={unknown ? "text-amber-300" : "text-emerald-300"} /><Metric label="Latest check" value={latest ? titleCase(latest.status) : "Not run"} /><Metric label="External orders" value={latest?.external_orders ?? 0} /></div><article className="panel mt-6 overflow-hidden"><div className="flex items-center gap-3 border-b border-slate-800 px-5 py-4"><Route className="h-5 w-5 text-violet-300" /><div><p className="eyebrow">Intent → lifecycle</p><h3 className="font-semibold text-white">Paper OMS ledger</h3></div></div>{orders.length ? <div className="table-scroll"><table className="terminal-table"><thead><tr><th>Instrument</th><th>Intent</th><th>Venue</th><th>Lifecycle</th><th>Filled</th><th>Updated</th></tr></thead><tbody>{orders.map((item) => <tr key={item.id}><td><strong>{item.instrument_token}</strong><span>{item.side} · {item.quantity}</span></td><td className="muted-cell">{item.idempotency_key.slice(0, 28)}</td><td>{item.venue}</td><td><span className={`status-pill ${item.status === "FILLED" ? "status-good" : item.status === "UNKNOWN" ? "status-warn" : "status-watch"}`}>{titleCase(item.status)}</span></td><td className="numeric">{item.filled_quantity}/{item.quantity}{item.average_fill_price !== null && <span> · ₹{formatPrice(item.average_fill_price)}</span>}</td><td className="muted-cell">{formatIstTimestamp(item.updated_at)}</td></tr>)}</tbody></table></div> : <div className="empty-inset m-5 p-8 text-center text-sm text-slate-400">OMS entries appear automatically when the scanner queues a paper entry. They cannot be created for a broker.</div>}</article></section>;
}
function Metric({ label, value, tone = "text-white" }: { label: string; value: string | number; tone?: string }) { return <article className="glass-inset rounded-md p-4"><p className="eyebrow">{label}</p><p className={`mt-2 numeric text-2xl font-semibold ${tone}`}>{value}</p></article>; }
