"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Eye, EyeOff, LockKeyhole, ShieldCheck } from "lucide-react";
import { api } from "./api";

export function LoginScreen() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setLoading(true); try { await api.login(email, password); router.replace("/"); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to sign in"); } finally { setLoading(false); } }
  return <main className="login-stage min-h-screen p-5 sm:p-8"><section className="mx-auto grid min-h-[calc(100vh-2.5rem)] max-w-6xl overflow-hidden rounded-2xl border border-slate-800 bg-terminal-900 shadow-2xl shadow-black/40 lg:grid-cols-[1.1fr_.9fr]"><div className="hidden flex-col justify-between border-r border-slate-800 bg-[radial-gradient(circle_at_top_left,_rgba(16,185,129,.15),_transparent_44%)] p-10 lg:flex"><div className="flex items-center gap-3 text-sm font-semibold tracking-[.2em] text-bullish"><span className="h-2.5 w-2.5 rounded-full bg-bullish" /> INTRADAY SENTINEL</div><div><p className="text-xs font-medium uppercase tracking-[.18em] text-emerald-400">Paper-first market intelligence</p><h1 className="mt-4 max-w-lg text-5xl font-semibold tracking-tight text-white">Trade decisions deserve a safety system.</h1><p className="mt-5 max-w-md text-base leading-7 text-slate-400">Signals, risk controls, and market data remain in paper mode until an explicit future release permits otherwise.</p></div><div className="flex items-center gap-3 text-sm text-slate-400"><ShieldCheck className="h-5 w-5 text-bullish" /> Live order execution is locked.</div></div><div className="flex items-center justify-center p-6 sm:p-12"><form onSubmit={submit} className="w-full max-w-sm"><div className="mb-10 lg:hidden text-sm font-semibold tracking-[.2em] text-bullish">INTRADAY SENTINEL</div><div className="mb-8"><h2 className="text-3xl font-semibold text-white">Welcome back</h2><p className="mt-2 text-sm text-slate-400">Sign in to your protected terminal.</p></div><label className="field-label" htmlFor="email">Email</label><input id="email" className="field-input" type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" required /><label className="field-label mt-5" htmlFor="password">Password</label><div className="relative"><input id="password" className="field-input pr-12" type={showPassword ? "text" : "password"} value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" minLength={8} required /><button type="button" onClick={() => setShowPassword((value) => !value)} className="absolute right-3 top-3 text-slate-500 hover:text-slate-200" aria-label="Toggle password visibility">{showPassword ? <EyeOff className="h-5 w-5" /> : <Eye className="h-5 w-5" />}</button></div>{error && <p role="alert" className="mt-4 rounded-md border border-rose-900 bg-rose-950/40 px-3 py-2 text-sm text-rose-300">{error}</p>}<button disabled={loading} className="primary-button mt-7 w-full" type="submit">{loading ? "Signing in…" : "Sign in"}<ArrowRight className="h-4 w-4" /></button><p className="mt-6 flex items-center justify-center gap-2 text-xs text-slate-500"><LockKeyhole className="h-3.5 w-3.5" /> Sessions use secure HttpOnly cookies.</p></form></div></section></main>;
}
