"use client";

import { RefreshCw, SlidersHorizontal } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";

import { api, type AuditLog, type BrokerControls, type TradingControls, type UserSession } from "../../components/api";
import { formatIstTimestamp } from "../../lib/formatting";

export function SettingsPanel({ controls, isAdmin, onSave, onChange, onMessage }: { controls: TradingControls; isAdmin: boolean; onSave: (event: FormEvent<HTMLFormElement>) => void; onChange: (key: keyof TradingControls, value: string) => void; onMessage: (message: string) => void }) {
  return <section><div className="page-toolbar"><div><p className="eyebrow">Configuration</p><h2 className="page-title">Paper risk controls</h2><p className="page-copy">Settings are stored server-side and changes are audit logged.</p></div></div><form onSubmit={onSave} className="panel mt-6 max-w-5xl p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(controls).map(([key, value]) => <label key={key} className="field-label capitalize">{key.replaceAll("_", " ")}<input disabled={!isAdmin} className="field-input mt-2 disabled:cursor-not-allowed disabled:opacity-50" type={typeof value === "number" ? "number" : "text"} step="any" value={value} onChange={(event) => onChange(key as keyof TradingControls, event.target.value)} /></label>)}</div>{isAdmin && <button className="primary-button mt-7" type="submit"><SlidersHorizontal className="h-4 w-4" />Save controls</button>}</form><BrokerSettingsCard isAdmin={isAdmin} onMessage={onMessage} /><SecurityPanel isAdmin={isAdmin} onMessage={onMessage} /></section>;
}

export function BrokerSettingsCard({ isAdmin, onMessage, focus }: { isAdmin: boolean; onMessage: (message: string) => void; focus?: "UPSTOX" | "FIRSTOCK" }) {
  const [controls, setControls] = useState<BrokerControls | null>(null);
  useEffect(() => { void api.brokerControls().then(setControls).catch((error: unknown) => onMessage(error instanceof Error ? error.message : "Could not load market-data settings")); }, [onMessage]);
  async function select(provider: "UPSTOX" | "FIRSTOCK" | "NONE") { if (!controls || !isAdmin) return; const next = { upstox_paper_enabled: provider === "UPSTOX", firstock_feed_enabled: provider === "FIRSTOCK" }; try { setControls(await api.updateBrokerControls(next)); onMessage(`Selected ${provider === "NONE" ? "no market-data connector" : `${provider} market data`}.`); } catch (error) { onMessage(error instanceof Error ? error.message : "Could not save market-data settings"); } }
  async function renewUpstox() { try { window.location.assign((await api.startUpstoxOAuth()).authorization_url); } catch (error) { onMessage(error instanceof Error ? error.message : "Could not start Upstox authorization"); } }
  const active = !controls ? "Loading…" : controls.upstox_paper_enabled ? "Upstox PAPER" : controls.firstock_feed_enabled ? "Firstock feed" : "Disabled";
  return <article className="panel mt-6 max-w-5xl p-5 sm:p-7"><p className="eyebrow">Market-data connectors</p><h3 className="mt-1 text-lg font-semibold text-white">Primary paper feed: {active}</h3><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Choose one connector at a time to prevent duplicate ticks, candles, and paper signals. Connector selection never enables live trading.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><button disabled={!isAdmin || !controls} onClick={() => void select("UPSTOX")} className={`secondary-button justify-center ${controls?.upstox_paper_enabled || focus === "UPSTOX" ? "border-emerald-500 text-emerald-300" : ""}`}>Use Upstox PAPER</button><button disabled={!isAdmin || !controls} onClick={() => void select("FIRSTOCK")} className={`secondary-button justify-center ${controls?.firstock_feed_enabled || focus === "FIRSTOCK" ? "border-emerald-500 text-emerald-300" : ""}`}>Use Firstock feed</button><button disabled={!isAdmin || !controls} onClick={() => void select("NONE")} className="secondary-button justify-center">Disable both</button></div>{isAdmin && <button onClick={() => void renewUpstox()} className="secondary-button mt-4"><RefreshCw className="h-4 w-4" />Renew Upstox access</button>}{!isAdmin && <p className="mt-4 text-xs text-slate-500">An administrator can change connector selection.</p>}</article>;
}

export function SecurityPanel({ isAdmin, onMessage, auditOnly = false }: { isAdmin: boolean; onMessage: (message: string) => void; auditOnly?: boolean }) {
  const [sessions, setSessions] = useState<UserSession[]>([]); const [audit, setAudit] = useState<AuditLog[]>([]);
  const load = useCallback(() => { if (!auditOnly) void api.sessions().then(setSessions).catch((error: unknown) => onMessage(error instanceof Error ? error.message : "Could not load sessions")); if (isAdmin) void api.auditLogs().then(setAudit).catch((error: unknown) => onMessage(error instanceof Error ? error.message : "Could not load audit history")); }, [auditOnly, isAdmin, onMessage]);
  useEffect(() => { load(); }, [load]);
  async function revoke(id: string) { try { await api.revokeSession(id); setSessions((current) => current.filter((item) => item.id !== id)); onMessage("Session revoked."); } catch (error) { onMessage(error instanceof Error ? error.message : "Could not revoke session"); } }
  return <section className={`mt-6 grid max-w-5xl gap-6 ${auditOnly ? "" : "xl:grid-cols-2"}`}>{!auditOnly && <article className="panel p-5 sm:p-7"><p className="eyebrow">Session management</p><h3 className="mt-1 text-lg font-semibold text-white">Active sessions</h3><div className="mt-5 space-y-3">{sessions.length ? sessions.map((item) => <div key={item.id} className="glass-inset rounded-md p-3 text-xs text-slate-400"><p className="truncate text-slate-200">{item.user_agent || "Unknown device"}</p><p className="mt-1">{item.ip_address || "Unknown IP"} · expires {formatIstTimestamp(item.expires_at)}</p><button onClick={() => void revoke(item.id)} className="mt-3 text-rose-300 hover:text-rose-200">Revoke session</button></div>) : <p className="text-sm text-slate-500">No active sessions found.</p>}</div></article>}{isAdmin && <article className="panel p-5 sm:p-7"><p className="eyebrow">Audit history</p><h3 className="mt-1 text-lg font-semibold text-white">Latest events</h3><div className="mt-5 space-y-3">{audit.length ? audit.slice(0, auditOnly ? 16 : 8).map((item) => <div key={item.id} className="border-b border-slate-800 pb-3 text-xs"><p className="text-slate-200">{item.event_type}</p><p className="mt-1 text-slate-500">{formatIstTimestamp(item.created_at)}{item.ip_address ? ` · ${item.ip_address}` : ""}</p></div>) : <p className="text-sm text-slate-500">No audit events found.</p>}</div></article>}</section>;
}
